
shapefiles: 
  AOI: "/home/hoehn/data/input/aoi_scenes.shp"
  Solar: "/home/hoehn/data/input/SolarParksAOI.shp"

model:
  patch_size: 128
  optimizer: Adam
  loss_function: binary_crossentropy
  epochs: 150

satellite:
  Sentinel1:
    name: Sentinel1 
    processing_level: LEVEL3
    product_type: CARD-BS-MC 
  Sentinel2:
    name: Sentinel2
    processing_level: LEVEL3
    product_type: L3-WASP
  search_criteria:
    start_date: "2021-05-01T00:00:00Z"
    end_date: "2021-07-31T23:59:59Z"
    cloud_cover: 5

prediction:
  Sentinel1: "/codede/Sentinel-1/SAR/CARD-BS-MC/2021/05/01/S1_CARD-BS-MC_202105_32UNC/"
  Sentinel2: "/codede/Sentinel-2/MSI/L3-WASP/2021/05/01/S2_L3_WASP_202105_32UNC/"
  
output_folder: "/home/hoehn/data/output/"