satellite:
  Sentinel1:
    name: Sentinel1 
    processing_level: LEVEL3
    product_type: CARD-BS-MC 
  Sentinel2:
    name: Sentinel2
    processing_level: LEVEL3
    product_type: L3-WASP
  search_criteria:
    start_date: "2021-01-01T00:00:00Z"
    end_date: "2021-12-31T23:59:59Z"
    cloud_cover: 30
  tiles_path: /home/hoehn/data/output/Sentinel-1/sentinel1_tiles.txt

shapefiles: 
  AOI: /home/hoehn/data/input/aoi_scenes.shp
  AOI_specSig: /home/hoehn/data/input/aoi_specSig.shp
  Solar: /home/hoehn/data/input/SolarParks.shp
  Solar_predict: /home/hoehn/data/input/solarParls_testTiles.shp
  landuse: /home/hoehn/data/input/landuse.shp

prediction:
  Sentinel1: /codede/Sentinel-1/SAR/CARD-BS-MC/2021/06/01/S1_CARD-BS-MC_202106_32UPE
  Sentinel2: /codede/Sentinel-2/MSI/L3-WASP/2021/06/01/S2_L3_WASP_202106_32UPE

model_parameter:
  patch_size: 128
  epochs: 100
  kfold: 5
  val_metric: dice_metric
  name: S1_128idx_kfold
  
indizes: True
output_folder: "/home/hoehn/data/output/Sentinel-1"
 
seed: 42