seed: 42

satellite:
  Sentinel1:
    name: Sentinel1 
    processing_level: LEVEL3
    product_type: CARD-BS-MC 
  search_criteria:
    start_date: "2021-06-01T00:00:00Z"
    end_date: "2021-07-31T23:59:59Z"
    cloud_cover: 5
    
shapefiles: 
  AOI: "/home/hoehn/data/input/aoi_scenes.shp"
  Solar: "/home/hoehn/data/input/SolarParks.shp"

model_parameter:
  patch_size: 128
  optimizer: Adam
  loss_function: binary_crossentropy
  epochs: 50

indizes: True

prediction:
  data:
    Sentinel1: "/codede/Sentinel-1/SAR/CARD-BS-MC/2021/07/01/S1_CARD-BS-MC_202107_32UPV"
    Sentinel2: "/codede/Sentinel-2/MSI/L3-WASP/2021/07/01/S2_L3_WASP_202107_32UPV"
    solar_path: "/home/hoehn/data/input/solarParks_predict.shp"  
  model:
    path: ""

output_folder: "/home/hoehn/data/output/Sentinel-1"